---
title:   "A doublesex model for reduced dimorphism - Supplementary Figure 1"
output:   html_notebook
by:       R. Coig
updated:  8/16/24
---
Notebook Summary: GGPlot code for Supplementary Figure 1
```{r,load required libraries}
library(ggplot2)
```
Loading in data
```{r,loading data}
rm(list = ls())
load('../_results/outlier-permutation.data')
```
Supplementary Figure 1 Plot
```{r}
FigS1<-ggplot(freq_melt, aes(x=value)) + 
  geom_histogram(bins=9,alpha=0.5) + 
  geom_vline(xintercept=8,linetype=3,linewidth=1) +
  #ggtitle("Distribution of Metabolite outlier frequencies") +
  xlab("Outliers per 91 metabolites")+
  ylab("Permutations")+
  scale_x_continuous(breaks=c(0:10)) +
  geom_text(x=8, y=1800, label="XXGA4",hjust=1.3)+
  geom_vline(xintercept=5,linetype=1,linewidth=0.5) +
  geom_text(x=5, y=3000, label="3",hjust=-0.5)+
  geom_vline(xintercept=4,linetype=1,linewidth=0.5) +
  geom_text(x=4, y=3000, label="3",hjust=-0.5) +
  geom_vline(xintercept=3,linetype=1,linewidth=0.5) +
  geom_text(x=3, y=3000, label="5",hjust=-0.5) +
  geom_vline(xintercept=2,linetype=1,linewidth=0.5) +
  geom_text(x=2, y=3000, label="7",hjust=-0.5)+
  geom_vline(xintercept=1,linetype=1,linewidth=0.5) +
  geom_text(x=1, y=3000, label="13",hjust=-0.5)+
  geom_vline(xintercept=0,linetype=1,linewidth=0.5) +
  geom_text(x=0, y=3000, label="19",hjust=-0.5)+
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5))
FigS1

ggsave("../_plots/FigS1.jpg", width = 5, height = 3)
```