---
title:   "A doublesex model for reduced dimorphism - Supplementary Figure 2"
output:   html_notebook
by:       R. Coig
updated:  8/16/24
---
Notebook Summary: GGPlot code for Supplementary Figure 2
```{r,load required libraries}
library(factoextra)#for PCA plots
```
Loading in data
```{r,loading data}
rm(list = ls())
load('../_results/PCA_combined.data')
```
Supplementary Figure 2 Plot 
```{r}
FigS2<-fviz_pca_ind(pca_all,
             col.ind = factor(Ttype, labels = c("Abdomen", "Head", "Thorax")), # color by groups with labels
             #palette = c("black",  "red"),
             addEllipses = TRUE, # Concentration ellipses
             axes = c(1,2),
             ellipse.type = "confidence",
             legend.title = "",
             repel = TRUE,
             label = "none",
             title = "PCA of all samples")+
  theme(plot.title = element_text(hjust = 0.5),legend.position = "bottom",
        panel.background = element_rect(fill = "white")) 

FigS2+xlab("PC1 (33.4%)")+ylab("PC2 (22.2%)")

ggsave("../_plots/FigS2.jpg", width = 5, height = 5)
```